# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/mt6785-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter begonia begoniain,$(TARGET_DEVICE)),)

endif
