# Copyright (C) 2019-2020 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/xiaomi/begonia/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/begonia

PRODUCT_COPY_FILES += \
    vendor/xiaomi/begonia/proprietary/vendor/bin/hw/vendor.nxp.hardware.nfc@1.1-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.nxp.hardware.nfc@1.1-service \
    vendor/xiaomi/begonia/proprietary/vendor/bin/pnscr:$(TARGET_COPY_OUT_VENDOR)/bin/pnscr \
    vendor/xiaomi/begonia/proprietary/vendor/etc/init/vendor.nxp.hardware.nfc@1.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.nxp.hardware.nfc@1.1-service.rc \
    vendor/xiaomi/begonia/proprietary/vendor/etc/nxp/Phone_bt_bt.bin:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Phone_bt_bt.bin \
    vendor/xiaomi/begonia/proprietary/vendor/etc/nxp/Phone_hsmic_hs.bin:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Phone_hsmic_hs.bin \
    vendor/xiaomi/begonia/proprietary/vendor/etc/nxp/Phone_mic_hp.bin:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Phone_mic_hp.bin \
    vendor/xiaomi/begonia/proprietary/vendor/etc/nxp/Phone_mic_recv.bin:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Phone_mic_recv.bin \
    vendor/xiaomi/begonia/proprietary/vendor/etc/nxp/Phone_mic_spk.bin:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Phone_mic_spk.bin \
    vendor/xiaomi/begonia/proprietary/vendor/etc/nxp/Phone_mic_spk_ev.bin:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Phone_mic_spk_ev.bin \
    vendor/xiaomi/begonia/proprietary/vendor/etc/nxp/Record_hs_cam.bin:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Record_hs_cam.bin \
    vendor/xiaomi/begonia/proprietary/vendor/etc/nxp/Record_hs_fast.bin:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Record_hs_fast.bin \
    vendor/xiaomi/begonia/proprietary/vendor/etc/nxp/Record_hs_normal.bin:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Record_hs_normal.bin \
    vendor/xiaomi/begonia/proprietary/vendor/etc/nxp/Record_hs_unprocess.bin:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Record_hs_unprocess.bin \
    vendor/xiaomi/begonia/proprietary/vendor/etc/nxp/Record_hs_vr.bin:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Record_hs_vr.bin \
    vendor/xiaomi/begonia/proprietary/vendor/etc/nxp/Record_mic_cam.bin:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Record_mic_cam.bin \
    vendor/xiaomi/begonia/proprietary/vendor/etc/nxp/Record_mic_fast.bin:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Record_mic_fast.bin \
    vendor/xiaomi/begonia/proprietary/vendor/etc/nxp/Record_mic_normal.bin:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Record_mic_normal.bin \
    vendor/xiaomi/begonia/proprietary/vendor/etc/nxp/Record_mic_unprocess.bin:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Record_mic_unprocess.bin \
    vendor/xiaomi/begonia/proprietary/vendor/etc/nxp/Record_mic_vr.bin:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/Record_mic_vr.bin \
    vendor/xiaomi/begonia/proprietary/vendor/etc/nxp/VoIP_bt_bt.bin:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/VoIP_bt_bt.bin \
    vendor/xiaomi/begonia/proprietary/vendor/etc/nxp/VoIP_hsmic_hs.bin:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/VoIP_hsmic_hs.bin \
    vendor/xiaomi/begonia/proprietary/vendor/etc/nxp/VoIP_hsmic_hs_game.bin:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/VoIP_hsmic_hs_game.bin \
    vendor/xiaomi/begonia/proprietary/vendor/etc/nxp/VoIP_mic_hp.bin:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/VoIP_mic_hp.bin \
    vendor/xiaomi/begonia/proprietary/vendor/etc/nxp/VoIP_mic_hp_game.bin:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/VoIP_mic_hp_game.bin \
    vendor/xiaomi/begonia/proprietary/vendor/etc/nxp/VoIP_mic_hs.bin:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/VoIP_mic_hs.bin \
    vendor/xiaomi/begonia/proprietary/vendor/etc/nxp/VoIP_mic_recv.bin:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/VoIP_mic_recv.bin \
    vendor/xiaomi/begonia/proprietary/vendor/etc/nxp/VoIP_mic_recv_game.bin:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/VoIP_mic_recv_game.bin \
    vendor/xiaomi/begonia/proprietary/vendor/etc/nxp/VoIP_mic_spk.bin:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/VoIP_mic_spk.bin \
    vendor/xiaomi/begonia/proprietary/vendor/etc/nxp/VoIP_mic_spk_game.bin:$(TARGET_COPY_OUT_VENDOR)/etc/nxp/VoIP_mic_spk_game.bin \
    vendor/xiaomi/begonia/proprietary/vendor/lib/hw/nfc_nci.nqx.default.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/nfc_nci.nqx.default.so \
    vendor/xiaomi/begonia/proprietary/vendor/lib/jcos_client.so:$(TARGET_COPY_OUT_VENDOR)/lib/jcos_client.so \
    vendor/xiaomi/begonia/proprietary/vendor/lib/lib_smartpa_nxp_ap.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib_smartpa_nxp_ap.so \
    vendor/xiaomi/begonia/proprietary/vendor/lib/libmlipay.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmlipay.so \
    vendor/xiaomi/begonia/proprietary/vendor/lib/libnxp_extamp_intf.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnxp_extamp_intf.so \
    vendor/xiaomi/begonia/proprietary/vendor/lib/libnxprecord.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnxprecord.so \
    vendor/xiaomi/begonia/proprietary/vendor/lib/libnxpspeech.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnxpspeech.so \
    vendor/xiaomi/begonia/proprietary/vendor/lib/libsn100u_fw.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsn100u_fw.so \
    vendor/xiaomi/begonia/proprietary/vendor/lib/libteeclientjni.so:$(TARGET_COPY_OUT_VENDOR)/lib/libteeclientjni.so \
    vendor/xiaomi/begonia/proprietary/vendor/lib/nfc_nci.nqx.default.hw.so:$(TARGET_COPY_OUT_VENDOR)/lib/nfc_nci.nqx.default.hw.so \
    vendor/xiaomi/begonia/proprietary/vendor/lib/se_extn_client.so:$(TARGET_COPY_OUT_VENDOR)/lib/se_extn_client.so \
    vendor/xiaomi/begonia/proprietary/vendor/lib/secure_element-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib/secure_element-impl.so \
    vendor/xiaomi/begonia/proprietary/vendor/lib/vendor.nxp.hardware.nfc@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib/vendor.nxp.hardware.nfc@1.0.so \
    vendor/xiaomi/begonia/proprietary/vendor/lib64/hw/nfc_nci.nqx.default.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/nfc_nci.nqx.default.so \
    vendor/xiaomi/begonia/proprietary/vendor/lib64/jcos_client.so:$(TARGET_COPY_OUT_VENDOR)/lib64/jcos_client.so \
    vendor/xiaomi/begonia/proprietary/vendor/lib64/lib_smartpa_nxp_ap.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib_smartpa_nxp_ap.so \
    vendor/xiaomi/begonia/proprietary/vendor/lib64/libgwsd-ril.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libgwsd-ril.so \
    vendor/xiaomi/begonia/proprietary/vendor/lib64/libmlipay.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmlipay.so \
    vendor/xiaomi/begonia/proprietary/vendor/lib64/libnxp_extamp_intf.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnxp_extamp_intf.so \
    vendor/xiaomi/begonia/proprietary/vendor/lib64/libnxprecord.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnxprecord.so \
    vendor/xiaomi/begonia/proprietary/vendor/lib64/libnxpspeech.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnxpspeech.so \
    vendor/xiaomi/begonia/proprietary/vendor/lib64/libteeclientjni.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libteeclientjni.so \
    vendor/xiaomi/begonia/proprietary/vendor/lib64/nfc_nci.nqx.default.hw.so:$(TARGET_COPY_OUT_VENDOR)/lib64/nfc_nci.nqx.default.hw.so \
    vendor/xiaomi/begonia/proprietary/vendor/lib64/se_extn_client.so:$(TARGET_COPY_OUT_VENDOR)/lib64/se_extn_client.so \
    vendor/xiaomi/begonia/proprietary/vendor/lib64/secure_element-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/secure_element-impl.so \
    vendor/xiaomi/begonia/proprietary/vendor/lib64/vendor.nxp.hardware.nfc@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib64/vendor.nxp.hardware.nfc@1.0.so
